server:
  port: 8085

logging:
  config: classpath:log4j2.yml

spring:
  application:
    name: gk5-ntm-sample
  profiles:
    include: api

cache:
  redis:
    host: 192.168.31.37
    port: 6379
    password:
    timeout: 50
    poolMaxTotal: 500
    poolMaxWaitMillis: -1
    poolMaxIdle: 150
    poolMinIdle: 100
    poolTestOnBorrow: true
