ntm:
  apiMap:
    base:
      # 1001 OSS直传场景
      base.ossUpload_1: ossUploadApiService,1,get
      # 1002 行政归属
      base.administrative_1: administrativeApiService,0,get
      # 1004 枚举
      base.menus_1: menusApiService,0,get
      # 1005 图片识别
      base.ocr_1: ocrApiService,0,get
      # 1011 验证码发送
      user.smsSend_1: smsSendApiService,0,get
      # 1015 身份证识别
      base.idCardOcr_1: idCardOcrApiService,0,get
      
    app:
      # 2001 登录
      user.loginBySms_1: loginBySmsApiService,0,post
      
    admin:
      standaloneDemo_1: standaloneDemoService,1,get